#pragma once

#define VIAL_KEYBOARD_UID {0x89, 0x36, 0x2A, 0xC7, 0xFA, 0xD8, 0x89, 0x45}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}
#define TAPPING_TERM 200
// #define TAPPING_TERM_PER_KEY
// #define VIAL_TAPPING_TERM_PER_KEY
/* #define HOLD_ON_OTHER_KEY_PRESS false */
/* #define HOLD_ON_OTHER_KEY_PRESS_PER_KEY */
#define PERMISSIVE_HOLD false
#define MAX_DEFERRED_EXECUTORS 10
#define TAPPING_TOGGLE 2

/* for the sm_td library */
// https://github.com/stasmarkin/sm_td
// #define SMTD_GLOBAL_TAP_TERM 400
// #define SMTD_GLOBAL_FOLLOWING_TAP_TERM 400
#define SMTD_GLOBAL_TAP_TERM 200
#define SMTD_GLOBAL_FOLLOWING_TAP_TERM 200
#define SMTD_GLOBAL_SEQUENCE_TERM 150
#define SMTD_GLOBAL_RELEASE_TERM 20
// #define SMTD_DEBUG_ENABLED

#define DYNAMIC_KEYMAP_LAYER_COUNT 12

#define VIAL_TAP_DANCE_ENTRIES 255

// Mouse:
// Accelerated mode:
#define MOUSEKEY_DELAY 5
#define MOUSEKEY_INTERVAL 20  // 16 if  ~60 fps
#define MOUSEKEY_MOVE_DELTA 8
#define MOUSEKEY_MAX_SPEED 8
#define MOUSEKEY_TIME_TO_MAX 50

#define MOUSEKEY_WHEEL_DELAY 10
#define MOUSEKEY_WHEEL_INTERVAL 80
#define MOUSEKEY_WHEEL_DELTA 1
#define MOUSEKEY_WHEEL_MAX_SPEED 8
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40

// Kinetic mode:
// #define MK_KINETIC_SPEED
// #define MOUSEKEY_DELAY 5
// #define MOUSEKEY_INTERVAL 10  // ~60 fps
// #define MOUSEKEY_MOVE_DELTA 16
// #define MOUSEKEY_INITIAL_SPEED 100
// #define MOUSEKEY_BASE_SPEED 5000
// #define MOUSEKEY_DECELERATED_SPEED 400
// #define MOUSEKEY_ACCELERATED_SPEED 3000
//
// #define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 16
// #define MOUSEKEY_WHEEL_BASE_MOVEMENTS 32
// #define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 48
// #define MOUSEKEY_WHEEL_DECELERATED_MOVEMENTS 8

// Constant mode:
#define MK_3_SPEED
#define MK_MOMENTARY_ACCEL
#define MK_C_OFFSET_UNMOD 12
#define MK_C_INTERVAL_UNMOD 16
#define MK_C_OFFSET_0 4
#define MK_C_INTERVAL_0 16
#define MK_C_OFFSET_1 24
#define MK_C_INTERVAL_1 16
#define MK_C_OFFSET_2 40
#define MK_C_INTERVAL_2 8
#define MK_W_OFFSET_UNMOD 1
#define MK_W_INTERVAL_UNMOD 40
#define MK_W_OFFSET_0 1
#define MK_W_INTERVAL_0 360
#define MK_W_OFFSET_1 1
#define MK_W_INTERVAL_1 120
#define MK_W_OFFSET_2 1
#define MK_W_INTERVAL_2 20

// Combined mode:
#define MK_COMBINED

// Inertia mode:
// #define MOUSEKEY_INERTIA
// #define MOUSEKEY_DELAY 150
// #define MOUSEKEY_INTERVAL 16
// #define MOUSEKEY_MAX_SPEED 32
// #define MOUSEKEY_TIME_TO_MAX 32
// #define MOUSEKEY_FRICTION 24
// #define MOUSEKEY_MOVE_DELTA 1
